# Generated by Django 5.0.3 on 2024-07-10 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_photo"),
    ]

    operations = [
        migrations.RemoveField(model_name="photo", name="caption",),
    ]
